### ISSUE TITLE
LOG-1500: Linux install script requires password

### ISSUE THREAD

**Issue by emptyflash** [loggly/install-script#82]
Trying to get everything configured to send logs to loggly from within a docker container. It seems that you have to provide your password to the configure linux script for it to work. Is this correct? If so what is the purpose of the token? 

I would personally prefer not to have my password stored in my Dockerfile and hosted on a github repo.

**Comment by nguyenfilip** [comment]
@emptyflash the purpose of the password is twofold:

1. test that the setup of loggly on the linux machine was successfull
2. in case AUTH TOKEN is not provided on the commandline, the AUTH token is retrieved using the password from loggly.com

I understand that you don't want to store the password in the Dockerfile, but why you are not passing your secrets (be it password or authtoken) as parameters to your starting container?

**Comment by emptyflash** [comment]
I forget the original context of this, but I think the reason I was having issues was because I was trying to run the install script in the build steps of the Dockerfile. 

The workaround back then was to run the install script as part of the docker image start up.

These days though, you can specify "build args" that solve this issue.
